version: "3.8"

services:
  mariadb:
    image: mariadb:user
    container_name: mariadb-container
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
  nginx:
    image: nginx:user
    container_name: nginx-container
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress:user
    container_name: wordpress-container
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      device: /home/malanglo/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      device: /home/malanglo/data/wordpress
      o : bind
      type : none

networks:
  inception:
    name: inception_network